# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: 'manas_vishal'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Manas Vishal"
params:
  mainSections:
    - posts
    - blog
# Site footer
footer:
  enable: false
  copyright:
    notice: 'Â© {year} Manas Vishal. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
  comment:
    # Choose a provider: giscus, disqus, commento, or '' to disable commenting
    provider: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
      theme: preferred_color_scheme
      language_code: en
      mapping: pathname
    disqus:
      # Paste the shortname from your Disqus dashboard.
      shortname: ''
      # Show comment count in page header? (true/false)
      show_count: true
    commento:
      # If you self-host Commento, enter your custom Commento URL here.
      url: ''

favicon: 'static/favicon.png'

